language: node_js
node_js:
- node
cache: npm
script: npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$TOKEN"
  local_dir: dist
  on:
    branch: master
env:
  global:
    secure: ZAaYEnbLkV9YhELJcQAexw3gKTPhh48y7V2q15f+jJFFW7J1a4ciHovTjlesrNm4gxN5UeQMVeRKTlnzUy8S17qvA5B9XMSA5O/I0/hS38AUvY6rz4crtubC0jIc7EhroISKrdc9jGskzDUOFRDqqqujwtkGM/Vj4E27UgbzTChYuylsxLxPpKgtx67ejMm8ErFEIERfJEX3rVwrpCcW/Gz395q990mMe1SVH2wBsqaurB2AStc5NKSW/1MZ9keGygR9Sn1CrPkUfxynrtXW0jL/ReY/NiwMo40wpyJgF51m40DzjZo9uPS4v9F5riGCpd9IS6hEhEBUbKev0DAQxnHs2KFI5hbka3/1IiIf9Hr+SgZz1EfLddJ4+eiwVpB/fbo5DxdwzikeFs5lZ26ZttIcaM6pyfgcaGaqztK9Ih+GDkVt3CV3LJTAT05ebN7AdBmzEd0X3uRsnNuLndLRmaNlWqr5NzE5Zo6Nyzo55qA11Zd+PVuVdx2BN7KgAAce+qYqySp/XoAs9O6XfGMuiuNsI78jKaJ3AhSw/YHXFeC29Y12N0s47Fv4SGFjic7Ep0Sk05/VY8L5hOCw6xRx9OxsTFuycRjnqGGvR5ZK8AwXvH8GnjlFhmTTQEe7BRsECqaNEaqC/mJt3xMd79fRVDX2KjZChi25MUxFrgXE6xE=
